// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://kauxpwhquojgxvmeyqoj.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImthdXhwd2hxdW9qZ3h2bWV5cW9qIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTMxOTU3NTAsImV4cCI6MjA2ODc3MTc1MH0.pi9gWeI6im7yIiORQyNmVIkEsRy67aVMnUsdvv5iikA";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});